import type { CropPreset } from '../schema'

export const developerCropPresets: CropPreset[] = [
  {
    id: 'dev-app-icon',
    category: 'developer',
    name: 'App Icon',
    description: '1024 × 1024 px · App Store / Play Store master icon',
    aspect: 1,
    outputWidth: 1024,
    outputHeight: 1024,
    format: 'png',
  },
  {
    id: 'dev-website-hero',
    category: 'developer',
    name: 'Website Hero',
    description: '1920 × 1080 px · full-width hero banner',
    aspect: 16 / 9,
    outputWidth: 1920,
    outputHeight: 1080,
    format: 'jpeg',
  },
  {
    id: 'dev-blog-cover',
    category: 'developer',
    name: 'Blog Cover',
    description: '1200 × 630 px · blog post cover image',
    aspect: 1200 / 630,
    outputWidth: 1200,
    outputHeight: 630,
    format: 'jpeg',
  },
  {
    id: 'dev-open-graph',
    category: 'developer',
    name: 'Open Graph',
    description: '1200 × 630 px · og:image link preview card',
    aspect: 1200 / 630,
    outputWidth: 1200,
    outputHeight: 630,
    format: 'jpeg',
  },
  {
    id: 'dev-favicon',
    category: 'developer',
    name: 'Favicon',
    description: '512 × 512 px master — downscale for 16/32/180 px favicons',
    aspect: 1,
    outputWidth: 512,
    outputHeight: 512,
    format: 'png',
  },
]
