import type { CropPreset } from '../schema'

export const socialCropPresets: CropPreset[] = [
  {
    id: 'social-instagram-post',
    category: 'social',
    name: 'Instagram Post',
    description: '1080 × 1080 px · square feed post',
    aspect: 1,
    outputWidth: 1080,
    outputHeight: 1080,
    format: 'jpeg',
  },
  {
    id: 'social-instagram-story',
    category: 'social',
    name: 'Instagram Story',
    description: '1080 × 1920 px · full-screen story',
    aspect: 9 / 16,
    outputWidth: 1080,
    outputHeight: 1920,
    format: 'jpeg',
  },
  {
    id: 'social-instagram-reel-cover',
    category: 'social',
    name: 'Instagram Reel Cover',
    description: '1080 × 1920 px · reel cover thumbnail',
    aspect: 9 / 16,
    outputWidth: 1080,
    outputHeight: 1920,
    format: 'jpeg',
  },
  {
    id: 'social-facebook-cover',
    category: 'social',
    name: 'Facebook Cover',
    description: '820 × 312 px · page cover photo',
    aspect: 820 / 312,
    outputWidth: 820,
    outputHeight: 312,
    format: 'jpeg',
  },
  {
    id: 'social-facebook-profile',
    category: 'social',
    name: 'Facebook Profile',
    description: '170 × 170 px · profile picture',
    aspect: 1,
    outputWidth: 170,
    outputHeight: 170,
    format: 'jpeg',
  },
  {
    id: 'social-linkedin-banner',
    category: 'social',
    name: 'LinkedIn Banner',
    description: '1584 × 396 px · profile background banner',
    aspect: 1584 / 396,
    outputWidth: 1584,
    outputHeight: 396,
    format: 'jpeg',
  },
  {
    id: 'social-linkedin-profile',
    category: 'social',
    name: 'LinkedIn Profile',
    description: '400 × 400 px · profile picture',
    aspect: 1,
    outputWidth: 400,
    outputHeight: 400,
    format: 'jpeg',
  },
  {
    id: 'social-twitter-header',
    category: 'social',
    name: 'Twitter Header',
    description: '1500 × 500 px · profile header banner',
    aspect: 3,
    outputWidth: 1500,
    outputHeight: 500,
    format: 'jpeg',
  },
  {
    id: 'social-youtube-thumbnail',
    category: 'social',
    name: 'YouTube Thumbnail',
    description: '1280 × 720 px · 16:9 video thumbnail',
    aspect: 16 / 9,
    outputWidth: 1280,
    outputHeight: 720,
    format: 'jpeg',
  },
  {
    id: 'social-youtube-channel-banner',
    category: 'social',
    name: 'YouTube Channel Banner',
    description: '2560 × 1440 px · safe area 1546 × 423 px centred',
    aspect: 2560 / 1440,
    outputWidth: 2560,
    outputHeight: 1440,
    format: 'jpeg',
  },
  {
    id: 'social-whatsapp-dp',
    category: 'social',
    name: 'WhatsApp DP',
    description: '500 × 500 px · display picture',
    aspect: 1,
    outputWidth: 500,
    outputHeight: 500,
    format: 'jpeg',
  },
]
